### PR TITLE
Add `npm run lint`

### LINKED ISSUE #13: Add ci to the build

### PR DESCRIPTION
**Pull request by mjangda**
Wired up to GitHub Actions support. Uses `eslines` to downgrade errors so we can fix issues incrementally.

Fixes #13

### CODE REVIEW

**Review by nickdaugherty — APPROVED** [review]
Yay! 🥳

**Comment by mjangda** [comment]
Hm, Netlify seems very sensitive to dependency issues.

**Comment by djalmaaraujo** [comment]
@mjangda Anything to do with these broken ci's?

**Comment by mjangda** [comment]
@djalmaaraujo I think we either need to downgrade Netlify to use Node 14 or fix the design system repo to work with Node 16+ (the latter is probably better).

**Comment by brunobasto** [comment]
I managed to make `npm install` work by adding

```
- name: Reconfigure git to use HTTPS authentication
      uses: GuillaumeFalourd/SSH-to-HTTPS@v1
```

to the workflow. It's failing now due to eslint issues. Need to fix code to get it to pass.

**Comment by mjangda** [comment]
Nice, thanks for the fixes @brunobasto! I think rather than adding the new action, it may be better to just to change how the repo is referenced in package.json.

https://docs.npmjs.com/cli/v8/configuring-npm/package-json#github-urls

**Review by djalmaaraujo — APPROVED** [review]
This is awesome, thanks

**Comment by mjangda** [comment]
:woohoo:

Thanks @brunobasto!

**Pull request merged**
