### PR TITLE
VIP Design Tokens update

### PR DESCRIPTION
**Pull request by djalmaaraujo**
### TODO:

- [x] Use font sizes from Figma
- [x] Use font weights from Figma
- [x] Use Border radius from Figma
- [x] Use spaces (padding, margin) from Figma
- [x] Update Input.background colors

All files inside `tokens` are pushed by Figma.

## Checklist

- [ ] This PR has good automated test coverage
- [x] The storybook for the component has been updated

## Steps to Test

Please look at the Preview from Netlify; everything should work the same.

### CODE REVIEW

**Comment by djalmaaraujo** [comment]
Reference: https://github.com/Automattic/vip-design-system/pull/218

**Comment by djalmaaraujo** [comment]
@dabowman We still need to update from Figma in a future PR:

- A better way to export Shadows, it's too complex to extract
- Should we use values like `#00000005` instead of rgba?
- Export font families with the proper fallbacks?
- Toggle styles have no meaning to the existing component. Can you check the Storybook and make color updates to the Toggle styles?
- We need to rethink about line-heights being in % percentage. It can be unstable: https://developer.mozilla.org/en-US/docs/Web/CSS/line-height#percentage. I updated the tokens, so it will update if you change to flat numbers.

**Review by kat3samsin — COMMENTED** [review]
Thank you for working on this massive PR 🥇 

Not sure if this legit bug or is it just storybook?
image

**Review by kat3samsin — CHANGES_REQUESTED** [review]
Thanks for the fix! I think you missed AutocompleteMulti.

**Review by kat3samsin — APPROVED** [review]
Awesome 🙌🏼

**Pull request merged**
